-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "AnimatePurchase",
    [2] = workspace:FindFirstChild("Ruixey's Tycoonkit 1.13.0").Tycoons:FindFirstChild("Car Rental 3").Purchased.MainFloor
}

game:GetService("ReplicatedStorage").TycoonEvent:FireServer(unpack(args))


game:GetService("ReplicatedStorage").TycoonEvent

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "AnimatePurchase",
    [2] = workspace:FindFirstChild("Ruixey's Tycoonkit 1.13.0").Tycoons:FindFirstChild("Car Rental 3").Purchased.Platform1
}

game:GetService("ReplicatedStorage").TycoonEvent:FireServer(unpack(args))




-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "1"
}

game:GetService("ReplicatedStorage").ClaimGift:FireServer(unpack(args))



local function plot()
    for i, v in pairs(workspace.)
